version: "3"
networks:
  micro-net:
    driver: bridge
volumes:
  api-gateway-node-modules:
  booking-service-node-modules:
  flights-service-node-modules:
services:
  api-gateway:
    build: ./API-Gateway
    image: singhsanket143/containerised-microservices_api-gateway
    networks:
      - micro-net
    ports:
      - "3001:3001"
    labels:
      kompose.service.type: LoadBalancer
  python-service:
    build: ./python-project
    image: singhsanket143/containerised-microservices_python-service
    networks:
      - micro-net
    ports:
      - "3005:3005"
    labels:
      kompose.service.type: LoadBalancer
  flights-service:
    build: ./Flights
    image: singhsanket143/containerised-microservices_flights-service
    networks:
      - micro-net
    ports: 
      - "3000:3000"
    labels:
      kompose.service.type: LoadBalancer
  booking-service:
    build: ./Flights-Booking-Service
    image: singhsanket143/containerised-microservices_booking-service
    networks:
      - micro-net
    ports:
      - "4000:4000"
    labels:
      kompose.service.type: LoadBalancer
    
# docker compose up -d // run all containers in detached mode kind of like -dit

# docker build -t python-app .
# docker run -it --init --name python_service --network microservice-network -p 3005:3005 -v "$(pwd)":/developer/pythonproject/flask-app  python-app:latest
# docker run -dit --init --name api_gateway1 --network microservice-network -p 3001:3001 -v "$(pwd)":/developer/nodejs/api-gateway -v api-gateway-node-modules:/developer/nodejs/api-gateway/node_modules api-gateway:latest 
# docker run -it --init --name flights_service --network microservice-network  -p 3000:3000 -v "$(pwd)":/developer/nodejs/flights-service -v flights-service-node-modules:/developer/nodejs/flights-service/node_modules flights-service:latest
#  docker run -it --init --name booking_service --network microservice-network  -p 4000:4000 -v "$(pwd)":/developer/nodejs/booking-service -v booking-service-node-modules:/developer/nodejs/booking-service/node_modules booking-service:latest